### PR TITLE
Add styles to repositories

### PR DESCRIPTION
**Pull request by Doomsdayrs**
CSS Styling has become a quickly emerging part of Shosetsu, let there be official support!

Also adds RepoAuthor, so they can be credited and appreciated.

- Minor adjustment to Test.kt

### CODE REVIEW

**Comment by TechnoJo4** [comment]
I don't think authors are really needed.

**Comment by Doomsdayrs** [comment]
> I don't think authors are really needed.

Why so? It helps with recognition of developers to Shosetsu

**Comment by Doomsdayrs** [comment]
@TechnoJo4 Do you accept the merge?

**Comment by TechnoJo4** [comment]
Sure

**Comment by Doomsdayrs** [comment]
@TechnoJo4 You have the honors then

**Pull request merged**
