### PR TITLE
Convert chapters property of Novel.Info to an array.

### PR DESCRIPTION
**Pull request by Doomsdayrs**
This allows us to remove an annoying conversion from Lua arrays to lists.

This is, quite a destructive commit as every single extension would have to be updated to support the change.

### CODE REVIEW

**Review by TechnoJo4 — APPROVED** [review]

**Comment by Doomsdayrs** [comment]
@TechnoJo4 I suppose we should go and update each extensions once I add this to Shosetsu?

Shosetsu will be updated immediately once this is added.

**Comment by TechnoJo4** [comment]
Create the extensions-side PR first, release the Shosetsu update and merge the extension updates at the same time.

**Comment by Doomsdayrs** [comment]
That is a bit difficult, How can we maintain backwards compatibility?

**Comment by TechnoJo4** [comment]
Add a LuaJ coercion from List to Array? not sure if you can even modify the lua->java coercions

**Comment by Doomsdayrs** [comment]
Just figured it out, by turning AsList() to just return the input

**Review by TechnoJo4 — APPROVED** [review]

**Pull request merged**
